main: com.zigdust09.feedback_plugin.FeedbackMain
name: Zigdust09Feedback
author: xWires
version: 0.1
api-version: 1.20
commands:
  feedback:
      description: Give feedback on this server!
      usage: /feedback <bugreport|suggestion> <text>
      permission: zigdust09.feedback
      permission-message: Sorry! We are not accepting feedback at the moment.